# Глобальные переменные, используемые для подготовки системы:
global_system_prepare_update_packages: false

# Глобальные переменные, используемые в том или ином виде во всех ролях, которые относятся к установке и настройке Vault (все режимы работы):
global_vault_current_version: "1.21.1"
global_vault_file_archive_checksum: "sha256:4088617653eba4ea341b6166130239fcbe42edc7839c7f7c6209d280948769c7"
global_vault_host_listening_address: 0.0.0.0
global_vault_host_listening_port: 8200
global_vault_lease_default_value: "24h"
global_vault_lease_max_value: "768h"

# Глобальные переменные, используемые для развертывания и настройки Transit Vault (все режимы работы):
global_vault_transit_backend_enable: false
global_vault_transit_backend_unseal_host: ""
global_vault_transit_backend_host_port: 8200 # 443, если он за Proxy и у вас SSL
global_vault_transit_backend_token: ""
global_vault_transit_backend_key_name: "autounseal"
global_vault_transit_backend_mount_path: "transit-backend-01/"
global_vault_transit_backend_disable_renewal: false
global_vault_transit_backend_tls_skip_verify: true # false, если у вас SSL

# Глобальные переменные, используемые для инициализации и распечатывания Vault (все режимы работы):
global_vault_unseal_secret_shares: 5
global_vault_unseal_secret_threshold: 3
global_vault_unseal_tls_skip_verify: true # false, если у вас SSL
global_vault_unseal_tls_disable: true # false, если у вас SSL

# Глобальные переменные, используемые в том или ином виде во всех ролях, которые относятся к установке и настройке Consul (все режимы работы):
global_consul_cluster_inventory_group: "consul_cluster"
global_consul_current_version: "1.22.1"
global_consul_file_archive_checksum: "sha256:91222c7ec141f1c2c92f6b732eeb0251220337e4c07c768cbc6ae633fef69733"
global_consul_host_listening_address: 0.0.0.0
global_consul_host_listening_dns_port: 8600
global_consul_host_listening_http_port: 8500
global_consul_host_listening_https_port: 8443

# Глобальные переменные, используемые для установки и настройки Nginx (все режимы работы):
global_nginx_enable_certbot_certificates: false
global_nginx_enable_certbot_certificates_email_address: "rurik@kitezh.slavic"
global_nginx_enable_certbot_certificates_command: "certbot certonly --nginx --noninteractive --agree-tos --email {{ global_nginx_enable_certbot_certificates_email_address }} --domains {{ global_nginx_host_domain }}"
global_nginx_host_domain: "molecule.local.vault"
global_nginx_set_http_scheme: "http"           # Client > Nginx
global_nginx_set_proxy_pass_scheme: "http"     # Nginx > Vault
global_nginx_set_cluster_vault_config: false
global_nginx_set_cluster_vault_addresses:
  - "10.0.0.1"
  - "10.0.0.2"
  - "10.0.0.3"
global_nginx_set_cluster_vault_weight:
  - "10"
  - "5"
  - "3"

# Глобальные переменные, используемые для установки и настройки HAProxy (все режимы работы):
global_haproxy_enable_certbot_certificates: false
global_haproxy_enable_certbot_certificates_email_address: "rurik@kitezh.slavic"
global_haproxy_enable_certbot_certificates_command: "certbot certonly --standalone --noninteractive --agree-tos --email {{ global_haproxy_enable_certbot_certificates_email_address }} --domains {{ global_haproxy_host_domain }}"
global_haproxy_host_domain: "molecule.local.vault"
global_haproxy_set_http_scheme: "http"         # Client > HAProxy 
global_haproxy_set_proxy_pass_scheme: "http"   # HAProxy > Vault
global_haproxy_set_cluster_vault_config: false
global_haproxy_set_cluster_vault_addresses:
  - "10.0.0.1"
  - "10.0.0.2"
  - "10.0.0.3"

# Molecule переменные, используемые для запуска тестов на базе драйвера EC2 в AWS:
aws_profile: "default"
aws_region: "eu-central-1"
aws_instance_type: "t3a.small"
aws_vpc_subnet_id: ""
aws_vpc_id: "vpc-cef0f9a7"
aws_key_method: "ec2"
aws_default_ssh_user: "ubuntu"
aws_local_private_key: "~/cosmos.pem"
aws_local_public_key: ""
aws_custom_key_name: ""
aws_security_group_name: ""
