---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: centos8
    image: mdd13/ansible-docker-redhat:centos8
    <<: &docker_platform
      pre_build_image: true
      privileged: true
      override_command: false
      cgroup_parent: docker.slice
      cgroupns_mode: host
      security_opts:
        - seccomp=unconfined

  - name: centos9
    image: mdd13/ansible-docker-redhat:centos9
    <<: *docker_platform

  - name: redhat8
    image: mdd13/ansible-docker-redhat:redhat8
    <<: *docker_platform

  - name: redhat9
    image: mdd13/ansible-docker-redhat:redhat9
    <<: *docker_platform

provisioner:
  name: ansible
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    links:
      group_vars: ../../../../group_vars/

verifier:
  name: ansible
