---
# Глобальные переменные, используемые для развертывания и настройки Manual Consul Agent:
global_consul_cluster_inventory_group: "consul_cluster"
global_consul_manual_agent_config: "consul_agent_config.hcl.j2"
global_consul_manual_agent_data_center: "dc1"
global_consul_manual_agent_retry_join:
  - "172.31.11.240"
  - "172.31.8.127"
  - "172.31.4.221"
global_consul_manual_agent_enable_https: false
global_consul_manual_agent_enable_tls_incoming: true
global_consul_manual_agent_enable_tls_outgoing: true
global_consul_manual_agent_enable_tls_server_hostname: true
