---
# Вызов роли для последующей установки и настройки Manual Consul Cluster для группы серверов на удаленных узлах:
- name: Install and configure Manual Consul Cluster on remote hosts
  gather_facts: true
  become: true
  any_errors_fatal: true
  hosts:
    - all

  # Вызов непосредственно самой роли Manual Consul Cluster для последующего развертывания кластера Consul в системе:
  roles:
    - manual-cluster-consul

  # Информирование о том, что Manual Consul Cluster был успешно установлен в системе:
  post_tasks:
    - name: Wait for Consul port to become available
      wait_for:
        host: 127.0.0.1
        port: "{{ global_consul_cluster_enable_https | ternary(global_consul_host_listening_https_port, global_consul_host_listening_http_port) }}"
        timeout: 30
      become: false

    - name: Check Consul for Availability
      uri:
        url: >-
          {{
            ( 'https' if global_consul_cluster_enable_https else 'http' ) ~ '://127.0.0.1:' ~
            ( global_consul_host_listening_https_port if global_consul_cluster_enable_https else global_consul_host_listening_http_port ) ~
            '/v1/status/leader'
          }}
        method: GET
        timeout: 10
        return_content: false
        status_code: [200]
        validate_certs: "{{ global_consul_cluster_enable_https }}"
        client_cert: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ inventory_hostname ~ '.crt.pem') if global_consul_cluster_enable_https else omit }}
        client_key: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ inventory_hostname ~ '.key.pem') if global_consul_cluster_enable_https else omit }}
        ca_path: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ global_system_internal_file_ca_certificate) if global_consul_cluster_enable_https else omit }}
