---
# Вызов роли для инициализации и распечатывания Cluster Vault на удаленных узлах:
- name: Init and Unseal Cluster Vault on remote hosts
  gather_facts: true
  become: true
  any_errors_fatal: true
  hosts:
    - all

  # Вызов непосредственно самой роли Unseal Cluster Vault для последующего распечатывания Vault в системе:
  roles:
    - system-unseal-cluster-vault

  # Информирование о том, что Cluster Vault был успешно проинициализирован и распечатан в запущенной ранее системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Cluster Vault has been successfully unsealed on the system"
