---
# Данный файл знаменует об успешном завершении запускаемых ранее тестов в Molecule:
- name: Verify our tests in Molecule
  hosts: all
  gather_facts: false
  tasks:
    # Чтение CA сертификата на делегированном узле:
    - name: Read CA certificate on Delegate Host
      community.crypto.x509_certificate_info:
        path: "{{ global_system_internal_dir_ca }}/{{ global_system_internal_file_ca_certificate }}"
      register: ca_certificate_info
      delegate_to: "{{ global_system_internal_delegate_host }}"
      run_once: true

    # Чтение выпущенных сертификатов на каждом узле в группе:
    - name: Read signed certificate on each Node
      community.crypto.x509_certificate_info:
        path: "{{ global_system_internal_dir_node_certificates }}/{{ inventory_hostname }}.crt.pem"
      register: node_certificate_info

    # Проверка того, что Issuer узла соответствует тому, что прописано в Subject CA сертификата:
    - name: Check if issuer of Node certificate matches CA subject
      ansible.builtin.assert:
        that:
          - node_certificate_info.issuer == ca_certificate_info.subject
        fail_msg: "Certificate on {{ inventory_hostname }} is not signed by the expected CA"
        success_msg: "Certificate on {{ inventory_hostname }} is valid and signed by expected CA"
