---
# Вызов предварительной роли system-prepare для полноценного запуска текущей:
- name: Import system-prepare role for running current role on SUSE family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Вызов предварительной роли system-docker для полноценного запуска текущей:
- name: Import system-docker role for running current role on SUSE family distro
  include_role:
    name: system-docker
    tasks_from: main
  when: not docker_already_installed

# Вызов файла install.yaml для установки Vault с помощью Docker согласно общей логике работы:
- name: Include common installation tasks on SUSE family distro
  include_tasks: install.yaml
