---
# Вызов роли для последующей установки и настройки Proxy Nginx в мануальном режиме на удаленных узлах:
- name: Install and configure Proxy Nginx on remote hosts
  gather_facts: true
  become: true
  become_method: sudo
  hosts:
    - all

  # Вызов непосредственно самой роли Proxy Nginx в мануальном режиме для последующего взаимодействия с Vault в системе:
  roles:
    - system-proxy-nginx

  # Информирование о том, что Proxy Nginx в мануальном режиме был успешно установлен в системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Nginx like a Proxy for Vault has been successfully installed on the system"
