---
# Вызов предварительной роли system-internal-certificates для полноценного запуска текущей роли в рамках заданных условий:
- name: Import system-internal-certificates role for running current role on Linux distro
  import_role:
    name: system-internal-certificates
    tasks_from: main
  when: global_consul_cluster_enable_https | bool

# Определение пути к Systemd unit файлу в зависимости от дистрибутива:
- name: Set systemd unit path based on distribution
  set_fact:
    local_consul_manual_cluster_systemd_path: >-
      {{ '/etc/systemd/system'
         if (ansible_distribution == 'Debian' and ansible_distribution_major_version | int < 12)
         else '/usr/lib/systemd/system' }}

# Создание группы с именем Consul:
- name: Create Consul Cluster group on Linux distro
  group:
    name: "{{ local_consul_manual_cluster_group }}"
    gid: "{{ local_consul_manual_cluster_group_id }}"
    state: present

# Создание пользователя с именем Consul:
- name: Create Consul Cluster user on Linux distro
  user:
    name: "{{ local_consul_manual_cluster_user }}"
    groups: "{{ local_consul_manual_cluster_group }}"
    uid: "{{ local_consul_manual_cluster_user_id }}"
    home: "{{ local_consul_manual_cluster_dir_data }}"
    shell: /sbin/nologin
    append: true

# Создание нескольких директорий для последующей работы с кластером Consul:
- name: Create Consul Cluster directories on Linux distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ local_consul_manual_cluster_dir_mode }}"
    owner: "{{ local_consul_manual_cluster_user }}"
    group: "{{ local_consul_manual_cluster_group }}"
  loop:
    - {path: "{{ local_consul_manual_cluster_dir_config }}"}
    - {path: "{{ local_consul_manual_cluster_dir_data }}"}

# Проверка текущей установленной версии Consul:
- name: Check installed Consul Cluster version on Linux distro
  command: "{{ local_consul_manual_cluster_path_binary }}/consul version"
  register: consul_installed_version
  changed_when: false
  failed_when: false

# Загрузка архива с бинарным файлом Consul из Интернета по прямой ссылке:
- name: Download Consul Cluster archive for future installation on Linux distro
  get_url:
    url: "{{ local_consul_manual_cluster_file_archive_link }}"
    mode: "{{ local_consul_manual_cluster_file_mode }}"
    dest: "/tmp/{{ local_consul_manual_cluster_file_archive_name }}"
    checksum: "{{ global_consul_file_archive_checksum }}"
    force: false
  register: consul_download_result
  retries: 3
  delay: 5
  until: consul_download_result is success
  when: >
    consul_installed_version.rc != 0 or
    global_consul_current_version not in consul_installed_version.stdout

# Извлечение архива и перемещение бинарного файла в соответствующую директорию:
- name: Unpack the Consul Cluster archive and move the binary file on Linux distro
  unarchive:
    src: "/tmp/{{ local_consul_manual_cluster_file_archive_name }}"
    dest: "{{ local_consul_manual_cluster_path_binary }}"
    mode: "0755"
    remote_src: true
  when: >
    consul_installed_version.rc != 0 or
    global_consul_current_version not in consul_installed_version.stdout
  notify: Restart Consul Cluster

# Копирование всех конфигурационных файлов Consul и их последующая отправка в соответствующие директории:
- name: Copy Consul Cluster configuration files from templates on Linux distro
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(local_consul_manual_cluster_file_mode) }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - src: "templates/{{ local_consul_manual_cluster_file_autocomplete_j2 }}"
      dest: "{{ local_consul_manual_cluster_file_autocomplete_path }}"
      mode: "{{ local_consul_manual_cluster_file_mode }}"
      owner: "{{ local_consul_manual_cluster_user }}"
      group: "{{ local_consul_manual_cluster_group }}"
    - src: "templates/{{ global_consul_cluster_server_config }}"
      dest: "{{ local_consul_manual_cluster_dir_config }}/{{ local_consul_manual_cluster_file_config }}"
      mode: "{{ local_consul_manual_cluster_file_mode }}"
      owner: "{{ local_consul_manual_cluster_user }}"
      group: "{{ local_consul_manual_cluster_group }}"
    - src: "templates/{{ local_consul_manual_cluster_file_systemd }}.j2"
      dest: "{{ local_consul_manual_cluster_systemd_path }}/{{ local_consul_manual_cluster_file_systemd }}"
      mode: "{{ local_consul_manual_cluster_file_mode }}"
      owner: "0"
      group: "0"
  notify: Restart Consul Cluster

# Запуск и добавление в автозагрузку сервиса Consul с помощью Systemd:
- name: Start Consul Cluster service on Linux distro
  systemd:
    name: consul
    state: started
    enabled: true
    daemon_reload: true

# Проверка того, что сертификат был создан на запущенном узле:
- name: Check that the certificate has been added on Linux distro
  shell: |
    openssl s_client -connect 127.0.0.1:{{ global_consul_host_listening_https_port }} -CAfile {{ global_system_internal_dir_node_certificates }}/{{ global_system_internal_file_ca_certificate }} < /dev/null 2>/dev/null
  register: openssl_status_check
  until: "'Verification: OK' in openssl_status_check.stdout"
  retries: 5
  delay: 5
  failed_when: "'Verification: OK' not in openssl_status_check.stdout"
  changed_when: false
  when: global_consul_cluster_enable_https | bool

# Финальный вывод после проверки работоспособности сертификата:
- name: Output the result on Linux distro
  debug:
    msg: "{{ openssl_status_check.stdout }}"
  when: global_consul_cluster_enable_https | bool
