---
name: Molecule Build Images

on:
  workflow_dispatch:

  push:
    paths:
      - 'dockerfiles/**'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [opensuse15.6, opensuse16.0, sles15.6, sles16.0, centos9, redhat9, redhat10, debian11, debian12, debian13, ubuntu22.04, ubuntu24.04]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Linting Dockerfile from List
        uses: hadolint/hadolint-action@v3.1.0
        env:
          DOCKERFILE_PROFILE: ${{ matrix.OS_VERSION }}
        with:
          recursive: true
          dockerfile: ./dockerfiles/${{ env.DOCKERFILE_PROFILE }}.dockerfile
          ignore: "DL3007,DL3008,DL3013,DL3033,DL3037,DL3041"

  build-suse-image:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-opensuse-image-matrix:
    needs: build-suse-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [opensuse15.6, opensuse16.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_HUB_USER: "mdd13"
          DOCKER_HUB_REPOSITORY: "ansible-docker-suse"
          IMAGE_TAG: ${{ matrix.OS_VERSION }}
        with:
          push: true
          context: ./dockerfiles/
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: ./dockerfiles/${{ env.IMAGE_TAG }}.dockerfile
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,scope=${{ env.IMAGE_TAG }},mode=max

  build-sles-image-matrix:
    needs: build-suse-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [sles15.6, sles16.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_HUB_USER: "mdd13"
          DOCKER_HUB_REPOSITORY: "ansible-docker-suse"
          IMAGE_TAG: ${{ matrix.OS_VERSION }}
        with:
          push: true
          context: ./dockerfiles/
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: ./dockerfiles/${{ env.IMAGE_TAG }}.dockerfile
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,scope=${{ env.IMAGE_TAG }},mode=max

  build-redhat-image:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-redhat-image-matrix:
    needs: build-redhat-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [centos9, redhat9, redhat10]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_HUB_USER: "mdd13"
          DOCKER_HUB_REPOSITORY: "ansible-docker-redhat"
          IMAGE_TAG: ${{ matrix.OS_VERSION }}
        with:
          push: true
          context: ./dockerfiles/
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: ./dockerfiles/${{ env.IMAGE_TAG }}.dockerfile
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,scope=${{ env.IMAGE_TAG }},mode=max

  build-debian-image:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-debian-image-matrix:
    needs: build-debian-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [debian11, debian12, debian13]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_HUB_USER: "mdd13"
          DOCKER_HUB_REPOSITORY: "ansible-docker-debian"
          IMAGE_TAG: ${{ matrix.OS_VERSION }}
        with:
          push: true
          context: ./dockerfiles/
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: ./dockerfiles/${{ env.IMAGE_TAG }}.dockerfile
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,scope=${{ env.IMAGE_TAG }},mode=max

  build-ubuntu-image:
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build-ubuntu-image-matrix:
    needs: build-ubuntu-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        OS_VERSION: [ubuntu22.04, ubuntu24.04]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_HUB_USER: "mdd13"
          DOCKER_HUB_REPOSITORY: "ansible-docker-ubuntu"
          IMAGE_TAG: ${{ matrix.OS_VERSION }}
        with:
          push: true
          context: ./dockerfiles/
          tags: ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: ./dockerfiles/${{ env.IMAGE_TAG }}.dockerfile
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,scope=${{ env.IMAGE_TAG }},mode=max
